apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-db
  template:
    metadata:
      labels:
        app: stock-db
    spec:
      containers:
        - name: stock-db
          image: redis:latest
          args: ["--requirepass", "redis"]  # Set Redis password
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pvc-stock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-stock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: stock-db
spec:
  selector:
    app: stock-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
